# Generated by Django 5.0.3 on 2024-03-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('company_owner', models.CharField(max_length=20)),
                ('total_emp', models.IntegerField()),
                ('city_pincode', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('OFF', 'Offline'), ('OL', 'Online')], max_length=20)),
                ('city_mode', models.CharField(choices=[('PUNE', 'Pune'), ('NASHIK', 'Nashik'), ('MUMBAI', 'Mumbai')], default='Pune', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
